### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by She1111** [gtluu/timsconvert#38]
Hi,

When I run test files on our own HPC, errors occurred like this. Are there any solutions to solve this problem?

**Comment by mwang87** [comment]
This nextflow workflow is not meant to run on your own HPC. I'd recommend folloiwng this guide:

https://github.com/gtluu/timsconvert#install-anaconda-on-linux

**Comment by mwang87** [comment]
I'd recommend chatting with your sys admins to get that version of GLIBC installed. Otherwise, i think you could put it into a singularity container.

**Comment by She1111** [comment]
Hi,

Thank you very much for your kind reply!

Regards,
Shel
