### ISSUE TITLE
WebVersion of timsConvert not working due to some (?) Python things? 

### ISSUE THREAD

**Issue by rugenni** [gtluu/timsconvert#59]
Hi, 

thank you for this great tool that I would love to use via the Web version at ucsd.edu. So I am trying to convert timsTOF data as .d folders with the TDF files etc. inside the specific folder. Hoewever, it does not seem to work. 

It seems that there is some something wrong with the server or the software, I attached my error log. Could you help me out? 

Many thanks,
Nils 

[Error_Message.txt](https://github.com/gtluu/timsconvert/files/14356795/Error_Message.txt)

**Comment by gtluu** [comment]
Hi @rugenni sorry to hear about the issues! I will try to look into this but should also note that the GNPS version is a bit outdated at the moment. In the meantime, the command line version should still be usable. Let me know if you have any questions about it. I'm currently looking into making a more user friendly version of TIMSCONVERT in the near future.

**Comment by gtluu** [comment]
As of now, no future updates are currently planned for the GNPS version of TIMSCONVERT.
